## Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6]
With Step:  [2 4 6]
Negative Indexing:  4


In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element: ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row and Specific column: ", arr_2d[:, 1])

Specific element:  6
Entire row:  [4 5 6]
Entire row and Specific column:  [2 5 8]


## Sorting


In [13]:
unsorted = np.array([3, 5, 3, 1, 7, 3, 8, 8])
print("Sorted Array: \n", np.sort(unsorted))

arr_2d_unsorted = np.array([[1, 4, 9], [6, 4, 8]])
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row: \n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array: 
 [1 3 3 3 5 7 8 8]
Sorted 2D array by column: 
 [[1 4 8]
 [6 4 9]]
Sorted 2D array by row: 
 [[1 4 9]
 [4 6 8]]


## Filter 

In [14]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### Filter with mask

In [16]:
mask = numbers > 5
print("Number greater than 5: ", numbers[mask])

Number greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [17]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)


[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# combined = arr1 + arr2
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibilty

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Compatibility shape: ", arr1.shape == arr2.shape)
print("Compatibility shape: ", arr1.shape == arr3.shape)
print("Compatibility shape: ", arr2.shape == arr3.shape)

Compatibility shape:  True
Compatibility shape:  True
Compatibility shape:  True


## Adding and Deleting Rows and Columns in NumPy

In [36]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print("Original Array: ", original)
print("\n")
print("With new row: ",with_new_array)
print("\n")

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column: ", with_new_col)

Original Array:  [[1 2]
 [3 4]]


With new row:  [[1 2]
 [3 4]
 [5 6]]


With new column:  [[1 2 7]
 [3 4 8]]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])
delete = np.delete(arr, 2)
print("Array after deletion: ", delete)

Array after deletion:  [1 2 4 5 6]
