# Numpy array and basics


In [19]:
import numpy as np
import time

### Created array from list

`np.array()` expects a single argument that is a list (or list of lists for 2D). You're passing two separate lists as two arguments, which is invalid.

In [20]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

# arr_2d = np.array([1, 2, 3], [4, 5, 6])  # ERROR
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"1D Array: {arr_2d}")

1D Array: [1 2 3 4 5]
1D Array: [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [21]:
py_list = [1, 2, 3]
print(f"Python array Multiplication: {py_list * 2}")

np_array = np.array([1, 2, 3])   # Element wise multiplication
print(f"Python array multiplication: {np_array * 2}")

start = time.time()
py_list = [i*2 for i in range(10000)]
print(f"\nList operation time: {time.time() - start}")

start = time.time()
np_array =np.arange(10000) * 2
print(f"\nNumpy operation time: {time.time() - start}")

Python array Multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]

List operation time: 2153.309623479843

Numpy operation time: 0.7308552265167236


## Creating array from scratch

In [22]:
zeros = np.zeros((3, 4))
print(f"Zeros Array: \n {zeros}")

ones = np.ones((3, 4))
print(f"Ones Array: \n {ones}")

full = np.full((2, 2), 7)
print(f"Full Array: \n {full}")

random = np.random.random((2, 3))
print(f"Random Array: \n {random}")

sequence = np.arange(0, 10, 2)
print(f"Sequence Array: \n {sequence}")

Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.43719935 0.65058474 0.34496315]
 [0.05337518 0.24778733 0.29594187]]
Sequence Array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [23]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)
print("\n")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: \n", matrix)
print("\n")

tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]


Matrix: 
 [[1 2 3]
 [4 5 6]]


Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array Properties

In [24]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape of Array: ", arr.shape)
print("Dimension of array: ", arr.ndim)
print("Size of Array: ", arr.size)
print("Dtype of Array: ", arr.dtype)

Shape of Array:  (2, 3)
Dimension of array:  2
Size of Array:  6
Dtype of Array:  int64


## Array Reshaping

In [30]:
arr = np.arange(12)
print("original Array: ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("\nFlattended Array: ", flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled Array: ", raveled)

# Transpose
transpose = reshaped.T
print("\nTransposed Array: ", transpose)


original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattended Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
